framework:
    asset_mapper:
        enabled: true
        paths:
            - '%kernel.project_dir%/assets'
            - '%kernel.project_dir%/assets/vendor'
        excluded_patterns:
            - '*/node_modules/*'

        server: true


when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
