nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
    forced_ssl:
        enabled: false

            # Headers de sécurité supplémentaires

    csp:
        report: # Section séparée, pas sous enforce
            default-src: [ 'self' ]
            script-src:
                - 'self'
                - 'js.stripe.com'
                - 'ga.jspm.io'
                - 'cdn.jsdelivr.net'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'data:'
                - 'blob:'
                - 'maps.googleapis.com'
                - 'maps.gstatic.com'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'cdn.jsdelivr.net'
                - 'fonts.googleapis.com'
            img-src: [ 'self', 'data:', 'https:', 'maps.googleapis.com', 'maps.gstatic.com', '*.googleapis.com', '*.gstatic.com' ]
            font-src: [ 'self', 'cdn.jsdelivr.net', 'fonts.gstatic.com' ]
            connect-src:
                - 'self'
                - 'api.stripe.com'
                - 'ga.jspm.io'
                - 'https:'
                - 'ws:'
                - 'wss:'
                - 'maps.googleapis.com'
            frame-src:
                - 'self'
                - 'https://www.google.com'
                - 'https://maps.google.com'
            object-src: [ 'none' ]
            base-uri: [ 'self' ]
#        enforce:
#            default-src: [ 'self' ]
#            script-src:
#                - 'self'
#                - 'js.stripe.com'
#                - 'ga.jspm.io'
#                - 'cdn.jsdelivr.net'
#                - 'unsafe-inline'
#            style-src:
#                - 'self'
#                - 'unsafe-inline'
#                - 'cdn.jsdelivr.net'
#            img-src: [ 'self', 'data:', 'https:' ]
#            font-src: [ 'self', 'cdn.jsdelivr.net' ]
#            connect-src:
#                - 'self'
#                - 'api.stripe.com'
#                - 'ga.jspm.io'
#                - 'https:'
#            frame-src:
#                - 'self'
#                - 'https://www.google.com'
#            object-src: [ 'none' ]
#            base-uri: [ 'self' ]

