# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    contact_picture_dir: '%kernel.project_dir%/assets/images/uploads/contact'
    participant_picture_dir: '%kernel.project_dir%/assets/images/uploads/utilisateurs'
    cheval_picture_dir: '%kernel.project_dir%/assets/images/uploads/chevaux'
    app.timezone: '%env(APP_TIMEZONE)%'
    stripe_base_url: '%env(STRIPE_BASE_URL)%'
    router.request_context.host: a1e2-2a01-08b-82c3-bc00-643b-15f2-af19-a9b.ngrok-free.app
    router.request_context.scheme: https
    app.mail_from: '%env(MAIL_FROM)%'
    app.contact_email: '%env(CONTACT_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'


    App\Kernel:
        calls:
            - [ setTimezone, [ '%app.timezone%' ] ]


    Stripe\StripeClient:
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'


    App\Service\NotificationService:
        arguments:
            $senderEmail: '%app.mail_from%'

    App\Controller\InscriptionPdfController:
        arguments:
            $uploadsDirectory: '%kernel.project_dir%/assets/images/uploads'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
